

#include "stm32g431xx.h"
#include "driver_spwm.h"
#include "cdefs.h"


void Driver_SPWM_GPIO_Init(void){
	
	//Enable clock for respective PORTS
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN;
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOCEN;
	
	//Config UH->PA8->TIM1_CH1->AFSEL8_AF6
	GPIOA->ODR   &=~GPIO_ODR_OD8;
	GPIOA->MODER &=~GPIO_MODER_MODE8;
	GPIOA->MODER |= GPIO_MODER_MODE8_0;
	GPIOA->AFR[1]&=~GPIO_AFRH_AFSEL8_Msk;
	GPIOA->AFR[1]|= 6 << GPIO_AFRH_AFSEL8_Pos;
	
	//Config UL->PC13->TIM1_CH1N->AFSEL13_AF4
	GPIOC->ODR   &=~GPIO_ODR_OD13;
	GPIOC->MODER &=~GPIO_MODER_MODE13;
	GPIOC->MODER |= GPIO_MODER_MODE13_0;
	GPIOC->AFR[1]&=~GPIO_AFRH_AFSEL13_Msk;
	GPIOC->AFR[1]|= 4 << GPIO_AFRH_AFSEL13_Pos;
	
	//Config VH->PA9->TIM1_CH2->AFSEL9_AF6
	GPIOA->ODR   &=~GPIO_ODR_OD9;
	GPIOA->MODER &=~GPIO_MODER_MODE9;
	GPIOA->MODER |= GPIO_MODER_MODE9_0;
	GPIOA->AFR[1]&=~GPIO_AFRH_AFSEL9_Msk;
	GPIOA->AFR[1]|= 6 << GPIO_AFRH_AFSEL9_Pos;
	
	//Config VL->PA12->TIM1_CH2N->AFSEL12_AF6
	GPIOA->ODR   &=~GPIO_ODR_OD12;
	GPIOA->MODER &=~GPIO_MODER_MODE12;
	GPIOA->MODER |= GPIO_MODER_MODE12_0;
	GPIOA->AFR[1]&=~GPIO_AFRH_AFSEL12_Msk;
	GPIOA->AFR[1]|= 6 << GPIO_AFRH_AFSEL12_Pos;
	
	//Config WH->PA10->TIM1_CH3->AFSEL10_AF6
	GPIOA->ODR   &=~GPIO_ODR_OD10;
	GPIOA->MODER &=~GPIO_MODER_MODE10;
	GPIOA->MODER |= GPIO_MODER_MODE10_0;
	GPIOA->AFR[1]&=~GPIO_AFRH_AFSEL10_Msk;
	GPIOA->AFR[1]|= 6 << GPIO_AFRH_AFSEL10_Pos;
	
	//Config WL->PB15->TIM1_CH3N->AFSEL15_AF4
	GPIOB->ODR   &=~GPIO_ODR_OD15;
	GPIOB->MODER &=~GPIO_MODER_MODE15;
	GPIOB->MODER |= GPIO_MODER_MODE15_0;
	GPIOB->AFR[1]&=~GPIO_AFRH_AFSEL15_Msk;
	GPIOB->AFR[1]|= 4 << GPIO_AFRH_AFSEL15_Pos;
}


void Driver_SPWM_Timer_Init(void){
	
	//Config Timer to generate PWM
	
	
	//Config UH->PA8->TIM1_CH1->AFSEL8_AF6
  
	
	//Config UL->PC13->TIM1_CH1N->AFSEL13_AF4

	
	//Config VH->PA9->TIM1_CH2->AFSEL9_AF6

	
	//Config VL->PA12->TIM1_CH2N->AFSEL12_AF6

	
	//Config WH->PA10->TIM1_CH3->AFSEL10_AF6

	
	//Config WL->PB15->TIM1_CH3N->AFSEL15_AF4

}